name: Weekly Report

on:
  schedule:
    - cron: "0 7 * * 1"  # Lundi 09:00 Paris l'été (07:00 UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run weekly report
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          python rapport.py

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report
          path: |
            output/**
            **/rapport*.md
            **/rapport*.pdf
